global:
  disableRequestsLimits: false

name: process-history-service-api

version: 1.1.0

deployProfile: prod

port: 8080

java:
  javaOpts: -Xms330m -Xmx330m -XX:+AlwaysPreTouch -XX:+UseG1GC

service:
  port: 8080

ingress:
  required: true
  site: proc-hist-svc-api

db:
  url: citus-master
  secret: citus-roles-secrets
  name: process_history
  port: 5432
  connectionTimeout: 4000

image:
  name: process-history-service-api
  version: latest

monitoring:
  namespace: openshift-monitoring
  prometheusScrapePath: /actuator/prometheus
  jobLabel: app

probes:
  liveness:
    path: /actuator/health/liveness
  readiness:
    path: /actuator/health/readiness

kafka:
  service: kafka-cluster-kafka-bootstrap:9093
  user: process-history-api-user
  clusterName: kafka-cluster
  sslEnabled: true
  sslUserKey: ${KAFKA_USER_KEYSTORE_KEY}
  sslUserCertificate: ${KAFKA_USER_KEYSTORE_CERTIFICATE}
  sslClusterCertificate: ${KAFKA_CLUSTER_TRUSTSTORE}

audit:
  kafka:
    topic: audit-events
    schemaRegistryUrl: http://kafka-schema-registry:8081

keycloak:
  realms:
    officer: officer-portal
    citizen: citizen-portal
    admin: admin
  certificatesEndpoint: /protocol/openid-connect/certs
